<?php 
set_include_path(get_include_path() . PATH_SEPARATOR . 'Classes');
require_once 'PHPExcel.php';
require_once 'PHPExcel/Writer/Excel2007.php';

$objExcel = new PHPExcel();

// $objWriter = new PHPExcel_Writer_Excel5($objExcel);
$objWriter = new PHPExcel_Writer_Excel2007($objExcel);    // 用于其他版本格式

$objProps = $objExcel->getProperties();
$objProps->setCreator("GONG CHENG");
$objProps->setLastModifiedBy("GONG CHENG");
$objProps->setTitle("Office XLS Test Document");
$objProps->setSubject("Office XLS Test Document, Demo");
$objProps->setDescription("Test document, generated by PHPExcel.");
$objProps->setKeywords("office excel PHPExcel");
$objProps->setCategory("Test");

$objExcel->setActiveSheetIndex(0);

$objActSheet = $objExcel->getActiveSheet();

include("includes/conn.php");
include("includes/link1.php");
$tables=$_POST['tables'];
$startid=$_POST['startid'];
$endid=$_POST['endid'];
$getcolumns=mysqli_query($link, "SHOW COLUMNS from $tables")
or die ("Could not match data because ".mysqli_error($link));
$numcolumns=mysqli_num_rows($getcolumns);
$columnarr=array();
$i=0;
while($getcolname=mysqli_fetch_array($getcolumns))
{
  $columnarr[$i]=$getcolname['Field'];
  if($getcolname['Key']=='PRI'){$primaryid=$getcolname['Field'];}
  $i=$i+1;
}
// print_r($columnarr);
// $keys = array_keys($columnarr);
$numcol=count($columnarr);
// print $numcol.'<br />';
// print $primaryid;
// print_r(array_keys($columnarr));
$tableinfo=mysqli_query($link, "SELECT * FROM $tables 
  WHERE $primaryid>='$startid' AND $primaryid<='$endid' ORDER BY $primaryid") 
or die ("Could not match data because ".mysqli_error($link));
$numtable=mysqli_num_rows($tableinfo);
if($numtable>0)
{
  $k=1;
  while ($getableinfo = mysqli_fetch_array($tableinfo))
  {
    $k=$k+1;
    // $keys = array_keys($columnarr); // Get the Column Names
    $min = ord('A'); // ord returns the ASCII value of the first character of string.
    $max = $min + $numcol;
    $firstChar = ""; // Initialize the First Character
    $abc = $min;   // Initialize our alphabetical counter
    for($j = $min, $num=0; $j < $max; ++$j, ++$num)
    {
      $col = $firstChar.chr($abc);   // This is the Column Label.
      $last_char = substr($col, -1);
      if ($last_char> "Z") // At the end of the alphabet. Time to Increment the first column letter.
      {
        $abc = $min; // Start Over
        if ($firstChar == "") // Deal with the first time.
          $firstChar = "A";
        else
        {
          $fchrOrd = ord($firstChar);// Get the value of the first character
          $fchrOrd++; // Move to the next one.
          $firstChar = chr($fchrOrd); // Reset the first character.
        }
        $col = $firstChar.chr($abc); // This is the column identifier
      }
       // 
      // print $col.$k.' ';
      // if($k==0) {print $columnarr[$num].' ';}
      // else print $getableinfo[$columnarr[$num]].' ';
      $objActSheet->setCellValue($col.$k,$getableinfo[$columnarr[$num]]);
      // $objActSheet->setCellValue($col.$k,'1');
      // print $col.$k.' '.$getableinfo[$columnarr[$num]].' ';
      // if($k==1) {$objActSheet->setCellValue($col.$k,$columnarr[$num]);}
        // Use the $col here.
      // else {$objActSheet->setCellValue($col.$k,$getableinfo[$columnarr[$num]]);}
        // Use the $col here.
      // print $col.'<br />';
      // print $getableinfo[$columnarr[$num]]."<br />"; 
      // print $col.'<br />';
      $abc++; // Move on to the next letter
    }
    // print '<br />';
  }
}

$outputFileName = $tables.".xlsx";
//到文件
// $objWriter->save($outputFileName);
//or
//到浏览器
header("Content-Type: application/force-download");
header("Content-Type: application/octet-stream");
header("Content-Type: application/download");
header('Content-Disposition:inline;filename="'.$outputFileName.'"');
header("Content-Transfer-Encoding: binary");
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Pragma: no-cache");
$objWriter->save('php://output');

?>