<?php

set_include_path(get_include_path() . PATH_SEPARATOR . 'Classes');
require_once 'PHPExcel.php';
$objExcel = new PHPExcel();

$objWriter = new PHPExcel_Writer_Excel5($objExcel);    // 用于其他版本格式

$objProps = $objExcel->getProperties();
$objProps->setCreator("GONG CHENG");
$objProps->setLastModifiedBy("GONG CHENG");
$objProps->setTitle("Office XLS Test Document");
$objProps->setSubject("Office XLS Test Document, Demo");
$objProps->setDescription("Test document, generated by PHPExcel.");
$objProps->setKeywords("office excel PHPExcel");
$objProps->setCategory("Test");

$objExcel->setActiveSheetIndex(0);

$objActSheet = $objExcel->getActiveSheet();

$objActSheet->setTitle('ATOUpload');

$objActSheet->setCellValue('A1',"Pre / Post Assessment");
$objActSheet->setCellValue('B1',"Class ID");
$objActSheet->setCellValue('C1',"Training Start Date (DD/MM/YYYY)");
$objActSheet->setCellValue('D1',">Training End Date (DD/MM/YYYY)");
$objActSheet->setCellValue('E1',"Course Code");
$objActSheet->setCellValue('F1',"Attendance Percentage");
$objActSheet->setCellValue('G1',"Transfer Flag (Yes/No)");
$objActSheet->setCellValue('H1',"Training Recommendation");
$objActSheet->setCellValue('I1',"ATO Org ID");
$objActSheet->setCellValue('J1',"EL");
$objActSheet->setCellValue('K1',"ER");
$objActSheet->setCellValue('L1',"EN");
$objActSheet->setCellValue('M1',"ES");
$objActSheet->setCellValue('N1',"EW");
$objActSheet->setCellValue('O1',"Salutation");
$objActSheet->setCellValue('P1',"ID Type (Select from dropdown list)");
$objActSheet->setCellValue('Q1',"NRIC/Fin No.");
$objActSheet->setCellValue('R1',"Expiry Date (DD/MM/YYYY)");
$objActSheet->setCellValue('S1',"SurName");
$objActSheet->setCellValue('T1',"GivenName");
$objActSheet->setCellValue('U1',"Name");
$objActSheet->setCellValue('V1',"Gender");
$objActSheet->setCellValue('W1',"DOB (DD/MM/YYYY)");
$objActSheet->setCellValue('X1',"Age");
$objActSheet->setCellValue('Y1',"Citizenship");
$objActSheet->setCellValue('Z1',"Nationality");
$objActSheet->setCellValue('AA1',"Ethnic Group");
$objActSheet->setCellValue('AB1',"Highest Chinese Education Level");
$objActSheet->setCellValue('AC1',"Highest Education Level");
$objActSheet->setCellValue('AD1',"Language Proficiency");
$objActSheet->setCellValue('AE1',"Blk");
$objActSheet->setCellValue('AF1',"Street Name");
$objActSheet->setCellValue('AG1',"#Floor - Unit No");
$objActSheet->setCellValue('AH1',"Building Name");
$objActSheet->setCellValue('AI1',"Postal Code");
$objActSheet->setCellValue('AJ1',"Contact No");
$objActSheet->setCellValue('AK1',"Email");
$objActSheet->setCellValue('AL1',"Employment Status");
$objActSheet->setCellValue('AM1',"Company Registration Type");
$objActSheet->setCellValue('AN1',"Company Name");
$objActSheet->setCellValue('AO1',"Company Registration No");
$objActSheet->setCellValue('AP1',"Industry Sector");
$objActSheet->setCellValue('AQ1',"Designation");
$objActSheet->setCellValue('AR1',"Salary Range");

include("includes/conn.php");
include("includes/link.php");
$ato_date=strtotime($_POST['ato_date']);
$ato_date1=$ato_date+24*3600;
$branch=$_POST['hiddenbranch'];
$atoresult=mysql_query("SELECT * FROM 
  ((SELECT * FROM ato_info WHERE UNIX_TIMESTAMP(examtime)>'$ato_date' 
  AND UNIX_TIMESTAMP(examtime)<='$ato_date1' 
  AND (branch='$branch' OR '$branch'='changchun')
  AND status!='delete' ORDER BY location, examtime) as new 
  LEFT JOIN student_info on 
  new.ic=student_info.ic) where 1")
  or die("Could not connect to mysql because ".mysql_error());

$place='changchun';
$time='0';
$examtime9=$ato_date+9*3600;
$examtime14=$ato_date+14*3600;
$examtime19=$ato_date+19*3600;
$i=1;
While($row=mysql_fetch_array($atoresult))
{
  $i=$i+1;
  if(($row['location']=='UN')&&($place!='UN'))
  {
    $objActSheet->setCellValue('A'.$i,"EUNOS:"); 
    $i=$i+1;
    $place='UN';
    $time='0';
  }
  if(($row['location']=='JE')&&($place!='JE'))
  {
    $objActSheet->setCellValue('A'.$i,"Jurong East:"); 
    $i=$i+1;
    $place='JE';
    $time='0';
  }
  if((strtotime($row['examtime'])==$examtime9)&&($time!='9'))
  {
    $objActSheet->setCellValue('A'.$i,"09:00:"); 
    $i=$i+1;
    $time='9';
  }
  if((strtotime($row['examtime'])==$examtime14)&&($time!='14'))
  {
    $objActSheet->setCellValue('A'.$i,"14:00:"); 
    $i=$i+1;
    $time='14';
  }
  if((strtotime($row['examtime'])==$examtime19)&&($time!='19'))
  {
    $objActSheet->setCellValue('A'.$i,"19:00:"); 
    $i=$i+1;
    $time='19';
  }
  $objActSheet->setCellValue('A'.$i,$row['prepost']);
  $objActSheet->setCellValue('B'.$i,"");
  $objActSheet->setCellValue('C'.$i,((!empty($row['start_date']))?date('d/m/Y',strtotime($row['start_date'])):''));
  $objActSheet->setCellValue('D'.$i,((!empty($row['end_date']))?date('d/m/Y',strtotime($row['end_date'])):''));
  $objActSheet->setCellValue('E'.$i,$row['coursecode']);
  $objActSheet->setCellValue('F'.$i,$row['attendance']);
  $objActSheet->setCellValue('G'.$i,$row['transfer']);
  $objActSheet->setCellValue('H'.$i,$row['recommend']);
  $objActSheet->setCellValue('I'.$i,$row['ATOOrgID']);
  $objActSheet->setCellValue('J'.$i,$row['EL']);
  $objActSheet->setCellValue('K'.$i,$row['ER']);
  $objActSheet->setCellValue('L'.$i,$row['EN']);
  $objActSheet->setCellValue('M'.$i,$row['ES']);
  $objActSheet->setCellValue('N'.$i,$row['EW']);
  $objActSheet->setCellValue('O'.$i,$row['salutation']);
  $objActSheet->setCellValue('P'.$i,$row['idtype']);
  $objActSheet->setCellValue('Q'.$i,$row['ic']);
  $objActSheet->setCellValue('R'.$i,
    (($row['expirydate']=='2038-01-01'||$row['expirydate']=='1970-01-01'||$row['expirydate']=='')?'':
      date('d/m/Y',strtotime($row['expirydate']))));
  $objActSheet->setCellValue('S'.$i,strtoupper($row['surname']));
  $objActSheet->setCellValue('T'.$i,strtoupper($row['givename']));
  $objActSheet->setCellValue('U'.$i,strtoupper($row['name']));
  $objActSheet->setCellValue('V'.$i,$row['gender']);
  $objActSheet->setCellValue('W'.$i,date('d/m/Y',strtotime($row['dateofbirth'])));
  if(!empty($row['dateofbirth'])&&$row['dateofbirth']!='SSA')
  {
    list($by,$bm,$bd)=explode('-',$row['dateofbirth']);
    $cm=date('n');
    $cd=date('j');
    $age=date('Y')-$by-1;
    if ($cm>$bm || ($cm==$bm && $cd>$bd)) $age++;
    $objActSheet->setCellValue('X'.$i,$age);
  }
  else
  {
    $objActSheet->setCellValue('X'.$i,$row['age']);
  }
  $objActSheet->setCellValue('Y'.$i,$row['citizenship']);
  $objActSheet->setCellValue('Z'.$i,$row['nationality']);
  $objActSheet->setCellValue('AA'.$i,$row['race']);
  $objActSheet->setCellValue('AB'.$i,$row['cnlevel']);
  $objActSheet->setCellValue('AC'.$i,$row['edulevel']);
  $objActSheet->setCellValue('AD'.$i,$row['lang']);
  $objActSheet->setCellValue('AE'.$i,$row['block']);
  $objActSheet->setCellValue('AF'.$i,$row['street']);
  $objActSheet->setCellValue('AG'.$i,$row['floorno']);
  $objActSheet->setCellValue('AH'.$i,$row['building']);
  $objActSheet->setCellValue('AI'.$i,$row['postcode']);
  $objActSheet->setCellValue('AJ'.$i,$row['tel']);
  $row['email']=(empty($row['email']))?($row['branch']."@changchun.edu.sg"):$row['email'];
  $objActSheet->setCellValue('AK'.$i,$row['email']);
  $objActSheet->setCellValue('AL'.$i,$row['employstatus']);
  $row['companystatus']=($row['companystatus']=='')?'OTHERS':$row['companystatus'];
  $objActSheet->setCellValue('AM'.$i,$row['companystatus']);
  $row['companyname']=($row['companyname']=='')?'NA':$row['companyname'];
  $objActSheet->setCellValue('AN'.$i,$row['companyname']);
  $row['companyregno']=($row['companyregno']=='')?'NA':$row['companyregno'];
  $objActSheet->setCellValue('AO'.$i,$row['companyregno']);
  $row['industry']=($row['industry']=='')?'1':$row['industry'];
  $objActSheet->setCellValue('AP'.$i,$row['industry']);
  $row['designation']=($row['designation']=='')?'10':$row['designation'];
  $objActSheet->setCellValue('AQ'.$i,$row['designation']);
  $row['salaryrange']=
  ($row['salaryrange']=='03a'||$row['salaryrange']=='03b'||$row['salaryrange']=='3')?'03':$row['salaryrange'];
  $row['salaryrange']=(strlen($row['salaryrange'])==1)?('0'.$row['salaryrange']):$row['salaryrange'];
  $objActSheet->setCellValueExplicit('AR'.$i,$row['salaryrange'],PHPExcel_Cell_DataType::TYPE_STRING);
}

$i=$i+2;
$objActSheet->setCellValue('A'.$i,'recordlist');
$i=$i+1;
$objActSheet->setCellValue('A'.$i,'Name');
$objActSheet->setCellValue('B'.$i,'NRIC');
$objActSheet->setCellValue('C'.$i,'Contact');
$objActSheet->setCellValue('D'.$i,'Remark');
$objActSheet->setCellValue('E'.$i,'R');
$objActSheet->setCellValue('F'.$i,'L');
$objActSheet->setCellValue('G'.$i,'S');
$objActSheet->setCellValue('H'.$i,'W');
$objActSheet->setCellValue('I'.$i,'N');
$objActSheet->setCellValue('J'.$i,'CMP');
$objActSheet->setCellValue('K'.$i,'CON');
$objActSheet->setCellValue('L'.$i,'WRI');
$objActSheet->setCellValue('M'.$i,'WPN');
$objActSheet->setCellValue('N'.$i,'Testype');
$objActSheet->setCellValue('O'.$i,'Location');
$objActSheet->setCellValue('P'.$i,'Code');

$crfresult=mysql_query("SELECT * FROM (ato_info LEFT JOIN student_info on 
  ato_info.ic=student_info.ic) WHERE UNIX_TIMESTAMP(ato_info.examtime)>'$ato_date' 
  AND UNIX_TIMESTAMP(ato_info.examtime)<='$ato_date1' 
  AND (branch='$branch' OR '$branch'='changchun')
  AND ato_info.status!='delete'
  ORDER BY ato_info.location, ato_info.examtime, ato_info.prepost")
  or die("Could not connect to mysql because ".mysql_error());

$place='changchun';
$time='0';
$examtime9=$ato_date+9*3600;
$examtime14=$ato_date+14*3600;
$examtime19=$ato_date+19*3600;
While($row=mysql_fetch_array($crfresult))
{
  $i=$i+1;
  if(($row['location']=='UN')&&($place!='UN'))
  {
    $objActSheet->setCellValue('A'.$i,"EUNOS:"); 
    $i=$i+1;
    $place='UN';
    $time='0';
  }
  if(($row['location']=='JE')&&($place!='JE'))
  {
    $objActSheet->setCellValue('A'.$i,"Jurong East:"); 
    $i=$i+1;
    $place='JE';
    $time='0';
  }
  if((strtotime($row['examtime'])==$examtime9)&&($time!='9'))
  {
    $objActSheet->setCellValue('A'.$i,"09:00:"); 
    $i=$i+1;
    $time='9';
  }
  if((strtotime($row['examtime'])==$examtime14)&&($time!='14'))
  {
    $objActSheet->setCellValue('A'.$i,"14:00:"); 
    $i=$i+1;
    $time='14';
  }
  if((strtotime($row['examtime'])==$examtime19)&&($time!='19'))
  {
    $objActSheet->setCellValue('A'.$i,"19:00:"); 
    $i=$i+1;
    $time='19';
  }
  $objActSheet->setCellValue('A'.$i,strtoupper($row['name']));
  $objActSheet->setCellValue('B'.$i,$row['ic']);
  $objActSheet->setCellValue('C'.$i,$row['tel']);
  $objActSheet->setCellValue('D'.$i,$row['remark']);
  $objActSheet->setCellValue('E'.$i,' ');
  $objActSheet->setCellValue('F'.$i,' ');
  $objActSheet->setCellValue('G'.$i,' ');
  $objActSheet->setCellValue('H'.$i,' ');
  $objActSheet->setCellValue('I'.$i,' ');
  $objActSheet->setCellValue('J'.$i,' ');
  $objActSheet->setCellValue('K'.$i,' ');
  $objActSheet->setCellValue('L'.$i,' ');
  $objActSheet->setCellValue('M'.$i,' ');
  $Testype=(($row['ER']=='Y')?'R':'')
  .(($row['EL']=='Y')?'L':'')
  .(($row['EN']=='Y')?'N':'')
  .(($row['ES']=='Y')?'S':'')
  .(($row['EW']=='Y')?'W':'');
  $objActSheet->setCellValue('N'.$i,$Testype);
  $objActSheet->setCellValue('O'.$i,$row['branch']);
  $objActSheet->setCellValue('P'.$i,$row['coursecode']);
}
$outputFileName = "ato.xls";
//到文件
// $objWriter->save($outputFileName);
//or
//到浏览器
header("Content-Type: application/force-download");
header("Content-Type: application/octet-stream");
header("Content-Type: application/download");
header('Content-Disposition:inline;filename="'.$outputFileName.'"');
header("Content-Transfer-Encoding: binary");
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Pragma: no-cache");

$objWriter->save('php://output');
?>
