<?
set_include_path(get_include_path() . PATH_SEPARATOR . 'Classes');
require_once 'PHPExcel.php';
$objExcel = new PHPExcel();

$objWriter = new PHPExcel_Writer_Excel5($objExcel);    // 用于其他版本格式

$objProps = $objExcel->getProperties();
$objProps->setCreator("GONG CHENG");
$objProps->setLastModifiedBy("GONG CHENG");
$objProps->setTitle("Office XLS Test Document");
$objProps->setSubject("Office XLS Test Document, Demo");
$objProps->setDescription("Test document, generated by PHPExcel.");
$objProps->setKeywords("office excel PHPExcel");
$objProps->setCategory("Test");

$objExcel->setActiveSheetIndex(0);

$objActSheet = $objExcel->getActiveSheet();

// $objActSheet->setTitle('ATOUpload');

$objActSheet->setCellValue('A1',"No.");
$objActSheet->setCellValue('B1',"Register Date");
$objActSheet->setCellValue('C1',"Register Location");
$objActSheet->setCellValue('D1',"Receipt No");
$objActSheet->setCellValue('E1',"Reg Form No.");
$objActSheet->setCellValue('F1',"Amt Paid");
$objActSheet->setCellValue('G1',"Attended Location");
$objActSheet->setCellValue('H1',"Class Attended Time");
$objActSheet->setCellValue('I1',"Class Code");
$objActSheet->setCellValue('J1',"Status");
$objActSheet->setCellValue('K1',"Phone: Mobile");
$objActSheet->setCellValue('L1',"Phone: Home");
$objActSheet->setCellValue('M1',"NRIC");
$objActSheet->setCellValue('N1',"Name");
$objActSheet->setCellValue('O1',"Gender");
$objActSheet->setCellValue('P1',"Nationality");
$objActSheet->setCellValue('Q1',"Birthday");
$objActSheet->setCellValue('R1',"Race");
$objActSheet->setCellValue('S1',"Designation");
$objActSheet->setCellValue('T1',"Language");
$objActSheet->setCellValue('U1',"Educational Level");
$objActSheet->setCellValue('V1',"Salary Range");
$objActSheet->setCellValue('W1',"Address: Home");
$objActSheet->setCellValue('X1',"Postal Code");
$objActSheet->setCellValue('Y1',"Pre-CAT Date (N,R,L)");
$objActSheet->setCellValue('Z1',"Pre-CAT Date (S,W)");
$objActSheet->setCellValue('AA1',"Pre-CAT (N)");
$objActSheet->setCellValue('AB1',"Pre-CAT (R)");
$objActSheet->setCellValue('AC1',"Pre-CAT (L)");
$objActSheet->setCellValue('AD1',"Pre-CAT (S)");
$objActSheet->setCellValue('AE1',"Pre-CAT (W)");
$objActSheet->setCellValue('AF1',"WPL Comprehensive");
$objActSheet->setCellValue('AG1',"WPL Conversational");
$objActSheet->setCellValue('AH1',"WPL Writing");
$objActSheet->setCellValue('AI1',"WPN");
//*************************************
//输出内容
//
include("includes/conn.php");
$link = mysqli_connect($dbhost, $dbuser, $dbpass, $dbname)
or die ("Could not select database because ".mysqli_error());
$classid=$_POST['hiddenclassid'];
$getbranch=mysqli_query($link, "SELECT branch FROM class_info WHERE classid='$classid'") 
or die ("Could not match data because ".mysqli_error());
$classbranch=mysqli_fetch_array($getbranch);
$branch=$classbranch['branch'];
$showstudent=mysqli_query($link, "SELECT *, date(rlupdated_at) as rlupdated_at,
date(swupdated_at) as swupdated_at FROM 
((SELECT * FROM sub_class_info WHERE classid='$classid' 
	and status!='delete') AS subclass 
LEFT JOIN student_info on subclass.ic=student_info.ic) WHERE 1")
or die ("Could not match data because ".mysqli_error());
$num_student = mysqli_num_rows($showstudent);
// echo $classid;
// echo $branch;
$i=1;
$j=$num_student+3;
if($num_student>0)
{
	$convertrace = array('CN' => 'Chinese', 'MY' =>'Malay', 
		'IN'=>'Indian', 'EU'=>'Eurasian','XX'=>'Other');
	$convertlang = array('CHI' => 'Chinese', 'ENG' =>'English', 
		'M'=>'Malay', 'T'=>'Tamil','O'=>'Others');
	$convertedu = array(
	  '1'=>'No Formal Qualification & Lower Primary',
	  '01'=>'No Formal Qualification & Lower Primary',
      '11'=>'Primary PSLE',
      '20'=>'Lower Secondary',
      '35'=>'ITE Skills Certification (ISC)',
      '31'=>'N Level or equivalent',
      '32'=>'O Level or equivalent',
      '41'=>'A Level or equivalent',
      '51'=>'NITEC/Post Nitec',
      '54'=>'WSQ Certificate',
      '52'=>'Higher NITEC',
      '55'=>'WSQ Higher Certificate',
      '53'=>'Master NITEC',
      '61'=>'Polytechnic Diploma',
      '73'=>'WSQ Advance Certificate',
      '74'=>'WSQ Diploma',
      '75'=>'WSQ Specialist Diploma',
      '70'=>'Professional Qualification & Other Diploma',
      '80'=>'University First Degree',
      '92'=>'WSQ Graduate Certificate',
      '93'=>'WSQ Graduate Diploma',
      '90'=>'University Post-graduate Diploma & Degree/Master/Doctorate',
      'XX'=>'Not Reported');
	$convertsalary = array('00' => '0', '01' =>'< $1,000', 
		'02'=>'$1,000 - $1,400', '03a'=>'$1,401 - $1,700','03b'=>'$1,701 - $2,000',
		'04'=>'$2,000 - $2,499', '05'=>'$2,000 - $3,499',
		'06'=>'$2,000 - $3,499', '07'=>'> $3,500',
		'0' => '0', '1' =>'< $1,000', 
		'2'=>'$1,000 - $1,499', '3'=>'$1,500 - $1,999',
		'4'=>'$2,000 - $2,499', '5'=>'$2,500 - $3,499', '6'=>'$2,500 - $3,499',
		'7'=>'> $3,500');
	$convertlevel = array('BEGINNERS' => 'B', 'INTERMEDIATE' => 'I',
		'ADVANCED' => 'A', 'NA' => 'NA', ''=>'NA');
	$convertidtype = array('1' => 'NRIC', '2' => 'FIN',
		'3' => 'OTHERS', '4' => 'OTHERS');
	$convertnationality = array('SG'=>'Singapore Citizen','CN'=>'Chinese','MY'=>'Malaysian','IN'=>'Indian',
			'ID'=>'Indonesian','AF'=>'Afghan','AL'=>'Albanian','DZ'=>'Algerian','US'=>'American',
			'AS'=>'American Samoa','AD'=>'Andorran','AO'=>'Angolan','AG'=>'Antigua',
			'AR'=>'Argentinian','AM'=>'Armenian','AU'=>'Australian','AT'=>'Austrian',
			'AZ'=>'Azerbaijani','BS'=>'Bahamas','BH'=>'Bahraini','BD'=>'Bangladeshi',
			'BB'=>'Barbados','BL'=>'Belarussian','BE'=>'Belgian','BZ'=>'Belize','BJ'=>'Benin',
			'BT'=>'Bhutan','BO'=>'Bolivian','BA'=>'Bosnian','BW'=>'Botswana','GC'=>'Br Dep Ter',
			'GG'=>'Br Nat. Overseas','GE'=>'Br Overseas Cit.','GJ'=>'Br Protected Pers.',
			'BR'=>'Brazilian','GB'=>'British','UK'=>'British Subject','BN'=>'Bruneian',
			'BG'=>'Bulgarian','BF'=>'Burkina Faso','BI'=>'Burundi','CF'=>'C`Tral African Rep',
			'KA'=>'Cambodian','CM'=>'Cameroon','CA'=>'Canadian','CV'=>'Cape Verde','TD'=>'Chadian',
			'CL'=>'Chilean','CO'=>'Colombian','KM'=>'Comoros','CG'=>'Congo','CK'=>'Cook Islands',
			'CR'=>'Costa Rican','CB'=>'Croatian','CU'=>'Cuban','CY'=>'Cypriot','CZ'=>'Czech',
			'CS'=>'Czechoslovak','DK'=>'Danish','DJ'=>'Djibouti','DM'=>'Dominica','DO'=>'Dominican',
			'NL'=>'Dutch','TP'=>'East Timorese','EC'=>'Ecuadorian','EG'=>'Egyptian',
			'GQ'=>'Equatorial Guinea','ER'=>'Eritrean','EN'=>'Estonian','ET'=>'Ethiopian',
			'FJ'=>'Fijian','PH'=>'Filipino','FI'=>'Finnish','FR'=>'French','GF'=>'French Guiana',
			'PF'=>'French Polynesia','GA'=>'Gabon','GM'=>'Gambian','GO'=>'Georgian','DG'=>'German',
			'DD'=>'German, East','DE'=>'German, West','GH'=>'Ghanaian','GD'=>'Grenadian',
			'GP'=>'Guadeloupe','GU'=>'Guam','GT'=>'Guatemala','GN'=>'Guinea','GW'=>'Guinea-Bissau',
			'GY'=>'Guyana','HN'=>'Honduran','HK'=>'Hong Kong','IS'=>'Iceland','IR'=>'Iranian',
			'IQ'=>'Iraqi','IE'=>'Irish','IL'=>'Israeli','IT'=>'Italian','CI'=>'Ivory Coast',
			'JM'=>'Jamaican','JP'=>'Japanese','JO'=>'Jordanian','KH'=>'Kampuchean','KZ'=>'Kazakh',
			'KE'=>'Kenyan','KG'=>'Kirghiz','KI'=>'Kiribati','KP'=>'Korean, North','KR'=>'Korean,
			South','KW'=>'Kuwaiti','KS'=>'Kyrghis','KY'=>'Kyrgyzstan','LA'=>'Laotian',
			'LV'=>'Latvian','LB'=>'Lebanese','LS'=>'Lesotho','LR'=>'Liberian','LY'=>'Libyan',
			'LI'=>'Liechtenstein','LH'=>'Lithuanian','LU'=>'Luxembourg','MO'=>'Macao',
			'MB'=>'Macedonia','MG'=>'Madagascar','MW'=>'Malawi','MV'=>'Maldivian','ML'=>'Mali',
			'MT'=>'Maltese','MH'=>'Marshallese','MQ'=>'Martinique','MR'=>'Mauritanean',
			'MU'=>'Mauritian','MX'=>'Mexican','MF'=>'Micronesian','MD'=>'Moldavian','MC'=>'Monaco
			','MN'=>'Mongolian','MA'=>'Moroccan','MZ'=>'Mozambique','BU'=>'Myanmar',
			'NA'=>'Namibia','NR'=>'Nauruan','NP'=>'Nepalese','NT'=>'Netherlands','AN'=>'Netherlands
			Antil.','NC'=>'New Caledonia','NZ'=>'New Zealander','NI'=>'Nicaraguan','NE'=>'Niger',
			'NG'=>'Nigerian','NU'=>'Niue','NS'=>'Non-S`Pore Citizen','NO'=>'Norwegian',
			'OM'=>'Oman','PC'=>'Pacific Is Trust T','PK'=>'Pakistani','PW'=>'Palauan',
			'PN'=>'Palestinian','PA'=>'Panamanian','PG'=>'Papua New Guinea','PY'=>'Paraguay',
			'PE'=>'Peruvian','PI'=>'Pitcairn','PL'=>'Polish','PT'=>'Portuguese','PR'=>'Puerto
			Rican','QA'=>'Qatar','RE'=>'Reunion','RO'=>'Romanian','SU'=>'Russian','RF'=>'Russian',
			'RW'=>'Rwanda','SV'=>'Salvadoran','WS'=>'Samoan','ST'=>'Sao Tome & Princi.','SA'=>'Saudi
			Arabian','SN'=>'Senegalese','SC'=>'Seychelles','SL'=>'Sierra Leone','SK'=>'Slovak',
			'SI'=>'Slovenian','SB'=>'Solomon Islands','SO'=>'Somali','ZA'=>'South African',
			'ES'=>'Spanish','LK'=>'Sri Lankan','SW'=>'St Kitts & Nevis','LC'=>'St. Lucia',
			'VC'=>'St. Vincent','SD'=>'Sudanese','SR'=>'Suriname','SZ'=>'Swazi','SE'=>'Swedish',
			'CH'=>'Swiss','SY'=>'Syrian','TJ'=>'Tadzhik','TW'=>'Taiwanese','TI'=>'Tajikistani',
			'TZ'=>'Tanzanian','TH'=>'Thai','TE'=>'Timorense','TG'=>'Togo','TK'=>'Tokelau Islands',
			'TO'=>'Tonga','TT'=>'Trinidad & Tobago','TN'=>'Tunisia','TR'=>'Turk','TM'=>'Turkmen',
			'TV'=>'Tuvalu','UG'=>'Ugandian','UR'=>'Ukrainian','AE'=>'United Arab Em.',
			'UN'=>'Unknown','HV'=>'Upper Volta','UY'=>'Uruguay','UZ'=>'Uzbek','VU'=>'Vanuatu',
			'VE'=>'Venezuelan','VN'=>'Vietnamese','WF'=>'Wallis And Futuna','EH'=>'Western Sahara',
			'YE'=>'Yemen Arab Rep','YD'=>'Yemen, South','YM'=>'Yemeni','YU'=>'Yugoslav',
			'ZR'=>'Zairan','ZM'=>'Zambian','ZW'=>'Zimbabwean','XX'=>'Other');
	$convertdesignation = array(
				'01'=>'Legislators, Senior Officials and Mangers',
				'1'=>'Legislators, Senior Officials and Mangers',
                '02'=>'Professionals',
				'2'=>'Professionals',
                '03'=>'Associate Professionals and Technicians',
				'3'=>'Associate Professionals and Technicians',
                '04'=>'Clerical Workers',
				'4'=>'Clerical Workers',
                '05'=>'Service Works and Shop and Market Sales Workers',
				'5'=>'Service Works and Shop and Market Sales Workers',
                '06'=>'Agricultural and Fishery Workers',
				'6'=>'Agricultural and Fishery Workers',
                '07'=>'Production Craftsmen & Related Workers',
				'7'=>'Production Craftsmen & Related Workers',
                '08'=>'Plan and Machine Operators and Assemblers',
				'8'=>'Plan and Machine Operators and Assemblers',
                '09'=>'Cleaners, Laborers and Related Workers',
				'9'=>'Cleaners, Laborers and Related Workers',
                '10'=>'Workers not classified by Occupation',
				''=>'Others');
	$objActSheet->setCellValue('A'.$j,"CRF");
	While($row=mysqli_fetch_array($showstudent))
	{
	  $i=$i+1;
	  $j=$j+1;
	  $objActSheet->setCellValue('A'.$i,($i-1));
	  $objActSheet->setCellValue('B'.$i,$row['reg_date']);
	  $objActSheet->setCellValue('C'.$i,$branch);
	  $objActSheet->setCellValue('D'.$i,$row['relatedreceipt']);
	  $objActSheet->setCellValue('E'.$i,$row['reg_no']);
	  $objActSheet->setCellValue('F'.$i,$row['relatedamount']);
	  $objActSheet->setCellValue('G'.$i,$branch);
	  $objActSheet->setCellValue('H'.$i,'');
	  $objActSheet->setCellValue('I'.$i,'');
	  $objActSheet->setCellValue('J'.$i,'');
	  $objActSheet->setCellValue('K'.$i,$row['tel']);
	  $objActSheet->setCellValue('L'.$i,$row['tel_home']);
	  $objActSheet->setCellValue('M'.$i,$row['ic']);
	  $objActSheet->setCellValue('N'.$i,$row['name']);
	  $row['gender']=($row['gender']=='F')?'Female':'Male';
	  $objActSheet->setCellValue('O'.$i,$row['gender']);
	  $objActSheet->setCellValue('P'.$i,$row['nationality']);
	  $dateofbirth=strtotime($row['dateofbirth']);
	  $row['dateofbirth']=date('dmY',$dateofbirth);
  	  $objActSheet->setCellValueExplicit('Q'.$i,$row['dateofbirth'],PHPExcel_Cell_DataType::TYPE_STRING);
	  $row['race']=$convertrace[$row['race']];
	  $objActSheet->setCellValue('R'.$i,$row['race']);
	  $row['designation']=$convertdesignation[$row['designation']];
  	  $objActSheet->setCellValue('S'.$i,$row['designation']);
	  $row['lang']=$convertlang[$row['lang']];
	  $objActSheet->setCellValue('T'.$i,$row['lang']);
	  $row['edulevel']=$convertedu[$row['edulevel']];
	  $objActSheet->setCellValue('U'.$i,$row['edulevel']);
	  $row['salaryrange']=$convertsalary[$row['salaryrange']];
	  $objActSheet->setCellValue('V'.$i,$row['salaryrange']);
	  $objActSheet->setCellValue('W'.$i,$row['address']);
	  $objActSheet->setCellValue('X'.$i,$row['postcode']);
	  $objActSheet->setCellValue('Y'.$i,$row['rlupdated_at']);
	  $objActSheet->setCellValue('Z'.$i,$row['swupdated_at']);
	  $objActSheet->setCellValue('AA'.$i,$row['ENRec']);
	  $objActSheet->setCellValue('AB'.$i,$row['ERRec']);
	  $objActSheet->setCellValue('AC'.$i,$row['ELRec']);
	  $objActSheet->setCellValue('AD'.$i,$row['ESRec']);
	  $objActSheet->setCellValue('AE'.$i,$row['EWRec']);
	  $row['CMP']=$convertlevel[$row['CMP']];
	  $objActSheet->setCellValue('AF'.$i,$row['CMP']);
	  $row['CON']=$convertlevel[$row['CON']];
	  $objActSheet->setCellValue('AG'.$i,$row['CON']);
	  $row['WRI']=$convertlevel[$row['WRI']];
	  $objActSheet->setCellValue('AH'.$i,$row['WRI']);
	  $row['WPN']=$convertlevel[$row['WPN']];
	  $objActSheet->setCellValue('AI'.$i,$row['WPN']);

	  $objActSheet->setCellValue('A'.$j,($i-1));
	  $row['idtype']=$convertidtype[$row['idtype']];
	  $objActSheet->setCellValue('B'.$j,$row['idtype']);
	  $objActSheet->setCellValue('C'.$j,$row['ic']);
	  $objActSheet->setCellValue('D'.$j,$row['name']);
  	  $objActSheet->setCellValue('E'.$j,$row['gender']);
  	  $objActSheet->setCellValue('F'.$j,$row['address']);
  	  $objActSheet->setCellValue('G'.$j,$row['tel']);
  	  $row['nationality']=$convertnationality[$row['nationality']];
	  $objActSheet->setCellValue('H'.$j,$row['nationality']);
      $objActSheet->setCellValueExplicit('I'.$j,$row['dateofbirth'],PHPExcel_Cell_DataType::TYPE_STRING);
  	  $objActSheet->setCellValue('J'.$j,$row['race']);
  	  $objActSheet->setCellValue('K'.$j,$row['designation']);
  	  $objActSheet->setCellValue('L'.$j,$row['lang']);
  	  $objActSheet->setCellValue('M'.$j,$row['edulevel']);
  	  $objActSheet->setCellValue('N'.$j,$row['salaryrange']);
	}
}


$outputFileName = "namelist.xls";
//到文件
// $objWriter->save($outputFileName);
//or
//到浏览器
header("Content-Type: application/force-download");
header("Content-Type: application/octet-stream");
header("Content-Type: application/download");
header('Content-Disposition:inline;filename="'.$outputFileName.'"');
header("Content-Transfer-Encoding: binary");
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Pragma: no-cache");
$objWriter->save('php://output');

?>
