<?php
set_include_path(get_include_path() . PATH_SEPARATOR . 'Classes');
require_once 'PHPExcel.php';
$objExcel = new PHPExcel();

$objWriter = new PHPExcel_Writer_Excel5($objExcel);    // 用于其他版本格式

$objProps = $objExcel->getProperties();
$objProps->setCreator("GONG CHENG");
$objProps->setLastModifiedBy("GONG CHENG");
$objProps->setTitle("Office XLS Test Document");
$objProps->setSubject("Office XLS Test Document, Demo");
$objProps->setDescription("Test document, generated by PHPExcel.");
$objProps->setKeywords("office excel PHPExcel");
$objProps->setCategory("Test");

$objExcel->setActiveSheetIndex(0);

$objActSheet = $objExcel->getActiveSheet();

$objActSheet->setTitle('ATOUpload');

$objActSheet->setCellValue('A1',"Pre / Post Assessment");
$objActSheet->setCellValue('B1',"Class ID");
$objActSheet->setCellValue('C1',"Training Start Date (DD/MM/YYYY)");
$objActSheet->setCellValue('D1',">Training End Date (DD/MM/YYYY)");
$objActSheet->setCellValue('E1',"Course Code");
$objActSheet->setCellValue('F1',"Attendance Percentage");
$objActSheet->setCellValue('G1',"Transfer Flag (Yes/No)");
$objActSheet->setCellValue('H1',"Training Recommendation");
$objActSheet->setCellValue('I1',"ATO Org ID");
$objActSheet->setCellValue('J1',"EL");
$objActSheet->setCellValue('K1',"ER");
$objActSheet->setCellValue('L1',"EN");
$objActSheet->setCellValue('M1',"ES");
$objActSheet->setCellValue('N1',"EW");
$objActSheet->setCellValue('O1',"Salutation");
$objActSheet->setCellValue('P1',"ID Type (Select from dropdown list)");
$objActSheet->setCellValue('Q1',"NRIC/Fin No.");
$objActSheet->setCellValue('R1',"Expiry Date (DD/MM/YYYY)");
$objActSheet->setCellValue('S1',"SurName");
$objActSheet->setCellValue('T1',"GivenName");
$objActSheet->setCellValue('U1',"Name");
$objActSheet->setCellValue('V1',"Gender");
$objActSheet->setCellValue('W1',"DOB (DD/MM/YYYY)");
$objActSheet->setCellValue('X1',"Age");
$objActSheet->setCellValue('Y1',"Citizenship");
$objActSheet->setCellValue('Z1',"Nationality");
$objActSheet->setCellValue('AA1',"Ethnic Group");
$objActSheet->setCellValue('AB1',"Highest Chinese Education Level");
$objActSheet->setCellValue('AC1',"Highest Education Level");
$objActSheet->setCellValue('AD1',"Language Proficiency");
$objActSheet->setCellValue('AE1',"Blk");
$objActSheet->setCellValue('AF1',"Street Name");
$objActSheet->setCellValue('AG1',"#Floor - Unit No");
$objActSheet->setCellValue('AH1',"Building Name");
$objActSheet->setCellValue('AI1',"Postal Code");
$objActSheet->setCellValue('AJ1',"Contact No");
$objActSheet->setCellValue('AK1',"Email");
$objActSheet->setCellValue('AL1',"Employment Status");
$objActSheet->setCellValue('AM1',"Company Registration Type");
$objActSheet->setCellValue('AN1',"Company Name");
$objActSheet->setCellValue('AO1',"Company Registration No");
$objActSheet->setCellValue('AP1',"Industry Sector");
$objActSheet->setCellValue('AQ1',"Designation");
$objActSheet->setCellValue('AR1',"Salary Range");
//*************************************
//输出内容
//
include("includes/conn.php");
include("includes/link.php");
$classid=$_POST['hiddenclassid'];
$showclasses=mysql_query("SELECT * FROM class_info 
WHERE classid='$classid' AND status!='delete'")
or die ("Could not match data because ".mysql_error());
$num_classes = mysql_num_rows($showclasses);
if($num_classes < 1)
{
  echo "没有id为".$classid."的班级，或者该班级属于其他分部。";
}
else
{
  $gedetails = mysql_fetch_array($showclasses);
  if(empty($gedetails['coursecode']))
  {
    echo "<script LANGUAGE='javascript'>alert('请输入班级代码。');</script>";
    return;
  }
  $coursecode = $gedetails['coursecode'];
  if(empty($gedetails['class_startdate']))
  {
    echo "<script LANGUAGE='javascript'>alert('请输入开课日期。');</script>";
    return;
  }
  $class_startdate = $gedetails['class_startdate'];
  if(empty($gedetails['class_endate']))
  {
    echo "<script LANGUAGE='javascript'>alert('请输入结课日期。');</script>";
    return;
  }
  $class_endate = $gedetails['class_endate'];
  if(empty($gedetails['classtype']))
  {
    echo "<script LANGUAGE='javascript'>alert('请输入班级类型。');</script>";
    return;
  }
  $classtype = $gedetails['classtype'];
  if($classtype=='encmp')
  {
    if(($gedetails['postcatlr'])=='2038-01-01 00:00:00')
    {
      echo "<script LANGUAGE='javascript'>alert('请输入听力阅读考试时间。');</script>";
      return;
    }
    $postcatlr = $gedetails['postcatlr'];
    if(empty($gedetails['lrlocation']))
    {
      echo "<script LANGUAGE='javascript'>alert('请输入听力阅读考试地点。');</script>";
      return;
    }
    $lrlocation = $gedetails['lrlocation'];
    if(($gedetails['postcatsw'])=='2038-01-01 00:00:00')
    {
      echo "<script LANGUAGE='javascript'>alert('请输入会话阅读考试时间。');</script>";
      return;
    }
    $postcatsw = $gedetails['postcatsw'];
    if(empty($gedetails['swlocation']))
    {
      echo "<script LANGUAGE='javascript'>alert('请输入会话阅读考试地点。');</script>";
      return;
    }
    $swlocation = $gedetails['swlocation'];
  }
  if($classtype=='encon')
  {
    if(($gedetails['postcatlr'])=='2038-01-01 00:00:00')
    {
      echo "<script LANGUAGE='javascript'>alert('请输入听力阅读考试时间。');</script>";
      return;
    }
    $postcatlr = $gedetails['postcatlr'];
    if(empty($gedetails['lrlocation']))
    {
      echo "<script LANGUAGE='javascript'>alert('请输入听力阅读考试地点。');</script>";
      return;
    }
  }
  $coursecode = $gedetails['coursecode'];
  $showstudent=mysql_query("SELECT * FROM 
    ((SELECT * FROM ato_info WHERE
  coursecode='$coursecode' ORDER BY examtime)as new
  LEFT JOIN student_info on new.ic=student_info.ic) WHERE 1")
  or die ("Could not match data because ".mysql_error());
  $num_student = mysql_num_rows($showstudent);
  
  $place='changchun';
  $time='0';
  $i=1;
  $date='0';
  While($row=mysql_fetch_array($showstudent))
  {
    $delete=($row['status']=='delete')?'已删除':'';
    if(date('Y-m-d',strtotime($row['examtime']))!=$date)
    {
      $date=date('Y-m-d',strtotime($row['examtime']));
      $i=$i+1;
      $objActSheet->setCellValue('A'.$i,$date);
    }
    $hour=date('H',strtotime($row['examtime']));
    $i=$i+1;
    if(($row['location']=='UN')&&($place!='UN'))
    {
      $objActSheet->setCellValue('A'.$i,"EUNOS:"); 
      $i=$i+1;
      $place='UN';
      $time='0';
    }
    if(($row['location']=='JE')&&($place!='JE'))
    {
      $objActSheet->setCellValue('A'.$i,"Jurong East:"); 
      $i=$i+1;
      $place='JE';
      $time='0';
    }
    if(($hour==9)&&($time!='9'))
    {
      $objActSheet->setCellValue('A'.$i,"09:00:"); 
      $i=$i+1;
      $time='9';
    }
    if(($hour==14)&&($time!='14'))
    {
      $objActSheet->setCellValue('A'.$i,"14:00:"); 
      $i=$i+1;
      $time='14';
    }
    if(($hour==19)&&($time!='19'))
    {
      $objActSheet->setCellValue('A'.$i,"19:00:"); 
      $i=$i+1;
      $time='19';
    }
    $objActSheet->setCellValue('A'.$i,$row['prepost']);
    $objActSheet->setCellValue('B'.$i,"");
    $objActSheet->setCellValue('C'.$i,((!empty($row['start_date']))?date('d/m/Y',strtotime($row['start_date'])):''));
    $objActSheet->setCellValue('D'.$i,((!empty($row['end_date']))?date('d/m/Y',strtotime($row['end_date'])):''));
    $objActSheet->setCellValue('E'.$i,$row['coursecode']);
    $objActSheet->setCellValue('F'.$i,$row['attendance']);
    $objActSheet->setCellValue('G'.$i,$row['transfer']);
    $objActSheet->setCellValue('H'.$i,$row['recommend']);
    $objActSheet->setCellValue('I'.$i,$row['ATOOrgID']);
    $objActSheet->setCellValue('J'.$i,$row['EL']);
    $objActSheet->setCellValue('K'.$i,$row['ER']);
    $objActSheet->setCellValue('L'.$i,$row['EN']);
    $objActSheet->setCellValue('M'.$i,$row['ES']);
    $objActSheet->setCellValue('N'.$i,$row['EW']);
    $objActSheet->setCellValue('O'.$i,$row['salutation']);
    $objActSheet->setCellValue('P'.$i,$row['idtype']);
    $objActSheet->setCellValue('Q'.$i,$row['ic']);
    $objActSheet->setCellValue('R'.$i,
      (($row['expirydate']=='2038-01-01')?'':date('d/m/Y',strtotime($row['expirydate']))));
    $objActSheet->setCellValue('S'.$i,strtoupper($row['surname']));
    $objActSheet->setCellValue('T'.$i,strtoupper($row['givename']));
    $objActSheet->setCellValue('U'.$i,strtoupper($row['name']));
    $objActSheet->setCellValue('V'.$i,$row['gender']);
    $objActSheet->setCellValue('W'.$i,date('d/m/Y',strtotime($row['dateofbirth'])));
    if(!empty($row['dateofbirth'])&&$row['dateofbirth']!='SSA')
    {
      list($by,$bm,$bd)=explode('-',$row['dateofbirth']);
      $cm=date('n');
      $cd=date('j');
      $age=date('Y')-$by-1;
      if ($cm>$bm || ($cm==$bm && $cd>$bd)) $age++;
      $objActSheet->setCellValue('X'.$i,$age);
    }
    else
    {
      $objActSheet->setCellValue('X'.$i,$row['age']);
    }
    $objActSheet->setCellValue('Y'.$i,$row['citizenship']);
    $objActSheet->setCellValue('Z'.$i,$row['nationality']);
    $objActSheet->setCellValue('AA'.$i,$row['race']);
    $objActSheet->setCellValue('AB'.$i,$row['cnlevel']);
    $objActSheet->setCellValue('AC'.$i,$row['edulevel']);
    $objActSheet->setCellValue('AD'.$i,$row['lang']);
    $objActSheet->setCellValue('AE'.$i,$row['block']);
    $objActSheet->setCellValue('AF'.$i,$row['street']);
    $objActSheet->setCellValue('AG'.$i,$row['floorno']);
    $objActSheet->setCellValue('AH'.$i,$row['building']);
    $objActSheet->setCellValue('AI'.$i,$row['postcode']);
    $objActSheet->setCellValue('AJ'.$i,$row['tel']);
    $row['email']=(empty($row['email']))?($row['branch']."@changchun.edu.sg"):$row['email'];
    $objActSheet->setCellValue('AK'.$i,$row['email']);
    $objActSheet->setCellValue('AL'.$i,$row['employstatus']);
    $row['companystatus']=($row['companystatus']=='')?'OTHERS':$row['companystatus'];
    $objActSheet->setCellValue('AM'.$i,$row['companystatus']);
    $row['companyname']=($row['companyname']=='')?'NA':$row['companyname'];
    $objActSheet->setCellValue('AN'.$i,$row['companyname']);
    $row['companyregno']=($row['companyregno']=='')?'NA':$row['companyregno'];
    $objActSheet->setCellValue('AO'.$i,$row['companyregno']);
    $row['industry']=($row['industry']=='')?'1':$row['industry'];
    $objActSheet->setCellValue('AP'.$i,$row['industry']);
    $row['designation']=($row['designation']=='')?'10':$row['designation'];
    $objActSheet->setCellValue('AQ'.$i,$row['designation']);
    $row['salaryrange']=
    ($row['salaryrange']=='03a'||$row['salaryrange']=='03b')?'03':$row['salaryrange'];
    $row['salaryrange']=(strlen($row['salaryrange'])==1)?('0'.$row['salaryrange']):$row['salaryrange'];
    $objActSheet->setCellValueExplicit('AR'.$i,$row['salaryrange'],PHPExcel_Cell_DataType::TYPE_STRING);
    $objActSheet->setCellValue('AS'.$i,$delete);
  }
}

$outputFileName = "ato.xls";
//到文件
// $objWriter->save($outputFileName);
//or
//到浏览器
header("Content-Type: application/force-download");
header("Content-Type: application/octet-stream");
header("Content-Type: application/download");
header('Content-Disposition:inline;filename="'.$outputFileName.'"');
header("Content-Transfer-Encoding: binary");
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Pragma: no-cache");
$objWriter->save('php://output');

?>