<?php

set_include_path(get_include_path() . PATH_SEPARATOR . 'Classes');
require_once 'PHPExcel.php';
$objExcel = new PHPExcel();

$objWriter = new PHPExcel_Writer_Excel5($objExcel);    // 用于其他版本格式

$objProps = $objExcel->getProperties();
$objProps->setCreator("GONG CHENG");
$objProps->setLastModifiedBy("GONG CHENG");
$objProps->setTitle("Office XLS Test Document");
$objProps->setSubject("Office XLS Test Document, Demo");
$objProps->setDescription("Test document, generated by PHPExcel.");
$objProps->setKeywords("office excel PHPExcel");
$objProps->setCategory("Test");

$objExcel->setActiveSheetIndex(0);

$objActSheet = $objExcel->getActiveSheet();

$objActSheet->setCellValue('A1',"考试日期  ");
$objActSheet->setCellValue('B1',"考试时间  ");
$objActSheet->setCellValue('C1',"星期几  ");
$objActSheet->setCellValue('D1',"座位数  ");
$objActSheet->setCellValue('E1',"考试地点  ");
include("includes/conn.php");
$link = mysql_connect($dbhost, $dbuser, $dbpass)
or die ("Could not connect to mysql because ".mysql_error());
mysql_select_db($dbname)
or die ("Could not select database because ".mysql_error());
mysql_query("SET NAMES UTF8");

$timestamp=strtotime("now");
$result = mysql_query("SELECT UNIX_TIMESTAMP(examdate) as examdate, 
      location,seatavailable,finish FROM exam_info where 
  UNIX_TIMESTAMP(examdate)>=$timestamp AND status='A' ORDER BY location, examdate")
or die ("Could not match data because ".mysql_error());

$i=1;
while($row = mysql_fetch_array($result))
{
  $examdate=$row['examdate'];
  $location=$row['location'];
  $seatavailable=$row['seatavailable'];
  $finish=$row['finish'];
  if($seatavailable>0&&$finish='on')
  {
    $i=$i+1;
    $objActSheet->setCellValue('A'.$i,date('Y-m-d',$examdate));
    $objActSheet->getColumnDimension('A')->setWidth(12);
    $objActSheet->setCellValue('B'.$i,date('h:00 A',$examdate));
    $objActSheet->setCellValue('C'.$i,date('D',$examdate));
    $objActSheet->setCellValue('D'.$i,$seatavailable);
    $objActSheet->setCellValue('E'.$i,$location);
  }
}

$outputFileName = "exam.xls";
//到文件
// $objWriter->save($outputFileName);
//or
//到浏览器
header("Content-Type: application/force-download");
header("Content-Type: application/octet-stream");
header("Content-Type: application/download");
header('Content-Disposition:inline;filename="'.$outputFileName.'"');
header("Content-Transfer-Encoding: binary");
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Pragma: no-cache");

$objWriter->save('php://output');
?>
