<?php 
set_include_path(get_include_path() . PATH_SEPARATOR . 'Classes');
require_once 'PHPExcel.php';
require_once 'PHPExcel/Writer/Excel2007.php';

$objExcel = new PHPExcel();

$objWriter = new PHPExcel_Writer_Excel2007($objExcel);    // 用于其他版本格式

$objProps = $objExcel->getProperties();
$objProps->setCreator("GONG CHENG");
$objProps->setLastModifiedBy("GONG CHENG");
$objProps->setTitle("Office XLS Test Document");
$objProps->setSubject("Office XLS Test Document, Demo");
$objProps->setDescription("Test document, generated by PHPExcel.");
$objProps->setKeywords("office excel PHPExcel");
$objProps->setCategory("Test");

$objExcel->setActiveSheetIndex(0);

$objActSheet = $objExcel->getActiveSheet();

$objActSheet->setCellValue('A1',"报名时间");
$objActSheet->setCellValue('B1',"报名地点");
$objActSheet->setCellValue('C1',"报名表号码");
$objActSheet->setCellValue('D1',"报名人");
$objActSheet->setCellValue('E1',"分部");
$objActSheet->setCellValue('F1',"学员IC");
$objActSheet->setCellValue('G1',"学员姓名");
$objActSheet->setCellValue('H1',"学员电话");
$objActSheet->setCellValue('I1',"家庭电话");
$objActSheet->setCellValue('J1',"性别");
$objActSheet->setCellValue('K1',"国籍");
$objActSheet->setCellValue('L1',"生日");
$objActSheet->setCellValue('M1',"地址");
$objActSheet->setCellValue('N1',"邮编");
$objActSheet->setCellValue('O1',"备注");
include("includes/conn.php");
include("includes/link1.php");
$reg_startdate=strtotime($_POST['reg_startdate']);
$reg_enddate=strtotime($_POST['reg_enddate']);
$branch=$_POST['hiddenbranch'];
$checkreginfo=mysqli_query($link, "SELECT * FROM 
    (reg_info LEFT JOIN student_info on reg_info.ic=student_info.ic) 
    where UNIX_TIMESTAMP(reg_date)>'$reg_startdate' 
  AND UNIX_TIMESTAMP(reg_date)<='$reg_enddate' AND 
  (branch='$branch' OR '$branch'='changchun') 
  AND reg_info.status!='delete' ORDER BY branch")
or die ("Could not match data because ".mysqli_error());
$numreg=mysqli_num_rows($checkreginfo);
if($numreg>0)
{
  $i=1;
  while ($getreginfo = mysqli_fetch_array($checkreginfo))
  {
    $i=$i+1;
    $objActSheet->setCellValue('A'.$i,$getreginfo['reg_date']);
    $objActSheet->setCellValue('B'.$i,$getreginfo['reg_location']);
    $objActSheet->setCellValue('C'.$i,$getreginfo['reg_no']);
    $objActSheet->setCellValue('D'.$i,$getreginfo['reg_op']);
    $objActSheet->setCellValue('E'.$i,$getreginfo['branch']);
    $objActSheet->setCellValue('F'.$i,$getreginfo['ic']);
    $objActSheet->setCellValue('G'.$i,$getreginfo['name']);
    $objActSheet->setCellValue('H'.$i,$getreginfo['tel']);
    $objActSheet->setCellValue('I'.$i,$getreginfo['tel_home']);
    $objActSheet->setCellValue('J'.$i,$getreginfo['gender']);
    $objActSheet->setCellValue('K'.$i,$getreginfo['nationality']);
    $objActSheet->setCellValue('L'.$i,$getreginfo['dateofbirth']);
    $objActSheet->setCellValue('M'.$i,$getreginfo['address']);
    $objActSheet->setCellValue('N'.$i,$getreginfo['postcode']);
    $objActSheet->setCellValue('O'.$i,$getreginfo['intro']);
  }
}
$outputFileName = "reg.xlsx";
//到文件
// $objWriter->save($outputFileName);
//or
//到浏览器
header("Content-Type: application/force-download");
header("Content-Type: application/octet-stream");
header("Content-Type: application/download");
header('Content-Disposition:inline;filename="'.$outputFileName.'"');
header("Content-Transfer-Encoding: binary");
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Pragma: no-cache");
$objWriter->save('php://output');


?>